# Generated by Django 5.2 on 2025-04-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('total_coordinates', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='animation.animationtype')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.CharField(max_length=255)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('image_format', models.CharField(default='png', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animation.animationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField(default=50)),
                ('json_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='animation.animationtype')),
            ],
        ),
    ]
